name: CI

on: [push, pull_request]

env:
  FOUNDRY_PROFILE: ci

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install deps
        run: forge install

      - name: check contract sizes
        run: forge build --sizes
        
      - name: diff gas snapshots
        run: forge snapshot --diff
        
      - name: Run tests
        run: | 
          forge clean
          forge test -vv
          forge test --gas-report
          
